streets = [
    'Ikorodu Road',
    'Awolowo Road',
    'Adeniran Ogunsanya Street',
    'Adeola Odeku Street',
    'Isaac John Street',
    'Bode Thomas Street',
    'Allen Avenue',
    'Toyin Street',
    'Herbert Macaulay Way',
    'Akin Adesola Street',
    'Opebi Road',
    'Idowu Taylor Street',
    'Broad Street',
    'Marina Street',
    'Ogunlana Drive',
    'Balogun Street',
    'Aromire Street',
    'Agidingbi Road',
    'Adeyemo Alakija Street',
    'Bishop Aboyade Cole Street',
    'Ademola Adetokunbo Street',
    'Sanusi Fafunwa Street',
    'Adeyemo Alakija Street',
    'Adeola Hopewell Street',
    'Ozumba Mbadiwe Avenue',
    'Adeyemi Lawson Street',
    'Adetokunbo Ademola Street',
    'Alexander Road',
    'Akinwunmi Street',
    'Yakubu Gowon Street',
    'Abacha Road',
    'Obafemi Awolowo Way',
    'Adegbola Street',
    'Adeniyi Jones Avenue',
    'Ogunnusi Road',
    'Ogun Street',
    'Oba Akran Avenue',
    'Kingsway Road',
    'Admiralty Way',
    'Festac Link Road',
    'Kudirat Abiola Way',
    'Agege Motor Road',
    'Admiralty Way',
    'Marina Street',
    'Eko Bridge',
    'Lagos Island',
    'Festac Town',
    'Saka Tinubu Street',
    'Opebi Road',
    'Admiralty Way',
    'Adelabu Street',
    'Osborne Road',
    'Adeyemo Alakija Street',
    'Adeniran Ogunsanya Street',
    'Oba Akran Avenue',
    'Ogunlana Drive',
    'Saka Tinubu Street',
    'Allen Avenue',
    'Ozumba Mbadiwe Avenue',
    'Alexander Road',
    'Sanusi Fafunwa Street',
    'Adeola Odeku Street'
]


cities = [
    'Lagos',
    'Abuja',
    'Kano',
    'Ibadan',
    'Port Harcourt',
    'Benin City',
    'Kaduna',
    'Jos',
    'Enugu',
    'Warri',
    'Aba',
    'Uyo',
    'Onitsha',
    'Calabar',
    'Maiduguri',
    'Zaria',
    'Abeokuta',
    'Sokoto',
    'Asaba',
    'Owerri',
    'Ilorin',
    'Ado-Ekiti',
    'Akure',
    'Makurdi',
    'Bauchi',
    'Katsina',
    'Minna',
    'Owo',
    'Osogbo',
    'Gombe',
    'Umuahia',
    'Ogbomosho',
    'Efon-Alaaye',
    'Ijebu-Ode',
    'Ikare',
    'Suleja',
    'Abakaliki',
    'Lafia',
    'Okene',
    'Iseyin',
    'Ondo',
    'Gboko',
    'Kumo',
    'Epe',
    'Gusau',
    'Funtua',
    'Bida',
    'Ife',
    'Ijero-Ekiti',
    'Effon-Alaiye',
    'Apomu',
    'Malumfashi',
    'Kaura Namoda',
    'Gwaram',
    'Kisi',
    'Kachia',
    'Lafiagi',
    'Potiskum',
    'Isieke',
    'Kaura Namoda',
    'Anka',
    'Bama',
    'Kamba',
    'Monguno',
    'Wukari',
    'Doma',
    'Yola',
    'Birnin Kebbi',
    'Martins',
    'Azare',
    'Gashua',
    'Bachaka',
    'Gwoza',
    'Ibi',
    'Birnin Gwari',
    'Argungu',
    'Kafanchan',
    'Gummi',
    'Rano',
    'Birnin Kudu',
    'Dikwa',
    'Katsina Ala',
    'Daura',
    'Wamba',
    'Kamba',
    'Kisi',
    'Gumel',
    ]
